{% set name = "pycolorbar" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycolorbar-{{ version }}.tar.gz
  sha256: d8f41b0928ce96b61d3cc4c18e94e50bc4ae729491070327a3cc5f309e56ee08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pydantic >=2.0.0
    - pyyaml

test:
  imports:
    - pycolorbar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiggi/pycolorbar
  summary: YAML-based colormap & colorbar settings for matplotlib and xarray
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
